server:
  port: 10086
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path: /manage
spring:
  application:
    name: manage
  datasource: #数据库相关
    url: jdbc:mysql://121.4.239.45:3306/order?serverTimezone=GMT+8&characterEncoding=utf-8
    username: roots
    password: qwe987@ZXC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #jackson对响应回去的日期参数进行格式化
    time-zone: GMT+8

portal:
  url: http://172.16.35.52:10010 #前端地址（用于跨域配置）

token:
  secret: order-manage #token加密私钥（很重要，注意保密）
  expire:
    time: 86400000 #token有效时长，单位毫秒 24*60*60*1000

system:
  masterCode: dujingsheng
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
